# Original database
states = [  {'state': 'alabama', 'abbreviation': 'al', 'capital': 'montgomery', 'population': 3894.0e+3, 'area': 51.7e+3, 'index': 22, 'cities': ['birmingham', 'mobile', 'montgomery', 'huntsville']},
            {'state': 'alaska', 'abbreviation': 'ak', 'capital': 'juneau', 'population': 401.8e+3, 'area': 591.0e+3, 'index': 49, 'cities': ['anchorage', 'fairbanks', 'juneau', 'sitka']},
            {'state': 'arizona', 'abbreviation': 'az', 'capital': 'phoenix', 'population': 2718.0e+3, 'area': 114.0e+3, 'index': 48, 'cities': ['phoenix', 'tucson', 'mesa', 'tempe']},
            {'state': 'arkansas', 'abbreviation': 'ar', 'capital': 'little rock', 'population': 2286.0e+3, 'area': 53.2e+3, 'index': 25, 'cities': ['little rock', 'fort smith', 'north little rock', 'pine bluff']},
            {'state': 'california', 'abbreviation': 'ca', 'capital': 'sacramento', 'population': 23.67e+6, 'area': 158.0e+3, 'index': 31, 'cities': ['los angeles', 'san diego', 'san francisco', 'san jose']},
            {'state': 'colorado', 'abbreviation': 'co', 'capital': 'denver', 'population': 2889.0e+3, 'area': 104.0e+3, 'index': 38, 'cities': ['denver', 'colorado springs', 'aurora', 'lakewood']},
            {'state': 'connecticut', 'abbreviation': 'ct', 'capital': 'hartford', 'population': 3107.0e+3, 'area': 5.02e+3, 'index': 5, 'cities': ['bridgeport', 'hartford', 'new haven', 'waterbury']},
            {'state': 'delaware', 'abbreviation': 'de', 'capital': 'dover', 'population': 594.0e+3, 'area': 2044, 'index': 1, 'cities': ['wilmington', 'newark', 'dover', 'brookside']},
            {'state': 'district of columbia', 'abbreviation':  'dc', 'capital': 'washington', 'population': 638.0e+3, 'area': 1100, 'index': 0, 'cities': ['tenleytown', 'washington', 'georgetown', 'duval circle']},
            {'state': 'florida', 'abbreviation': 'fl', 'capital': 'tallahassee', 'population': 9746.0e+3, 'area': 68664, 'index': 27, 'cities': ['jacksonville', 'miami', 'tampa', 'st. petersburg']},
            {'state': 'georgia', 'abbreviation': 'ga', 'capital': 'atlanta', 'population': 5463.0e+3, 'area': 58.9e+3, 'index': 4, 'cities': ['atlanta', 'columbus', 'savannah', 'macon']},
            {'state': 'hawaii', 'abbreviation': 'hi', 'capital': 'honolulu', 'population': 964.0e+3, 'area': 6471, 'index': 50, 'cities': ['honolulu', 'ewa', 'koolaupoko', 'wahiawa']},
            {'state': 'idaho', 'abbreviation': 'id', 'capital': 'boise', 'population': 944.0e+3, 'area': 83.0e+3, 'index': 43, 'cities': ['boise', 'pocatello', 'idaho falls', 'lewiston']},
            {'state': 'illinois', 'abbreviation': 'il', 'capital': 'springfield', 'population': 11.4e+6, 'area': 56.3e+3, 'index': 21, 'cities': ['chicago', 'rockford', 'peoria', 'springfield']},
            {'state': 'indiana', 'abbreviation': 'in', 'capital': 'indianapolis', 'population': 5490.0e+3, 'area': 36.2e+3, 'index': 19, 'cities': ['indianapolis', 'fort wayne', 'gary', 'evansville']},
            {'state': 'iowa', 'abbreviation': 'ia', 'capital': 'des moines', 'population': 2913.0e+3, 'area': 56.3e+3, 'index': 29, 'cities': ['des moines', 'cedar rapids', 'davenport', 'sioux city']},
            {'state': 'kansas', 'abbreviation': 'ks', 'capital': 'topeka', 'population': 2364.0e+3, 'area': 82.3e+3, 'index': 34, 'cities': ['wichita', 'kansas city', 'topeka', 'overland park']},
            {'state': 'kentucky', 'abbreviation': 'ky', 'capital': 'frankfort', 'population': 2364.0e+3, 'area': 82.3e+3, 'index': 15, 'cities': ['louisville', 'lexington', 'owensboro', 'covington']},
            {'state': 'louisiana', 'abbreviation': 'la', 'capital': 'baton rouge', 'population': 4206.0e+3, 'area': 47.7e+3, 'index': 18, 'cities': ['new orleans', 'baton rouge', 'shreveport', 'metairie']},
            {'state': 'maine', 'abbreviation': 'me', 'capital': 'augusta', 'population': 1125.0e+3, 'area': 33265, 'index': 23, 'cities': ['portland', 'lewiston', 'bangor', 'auburn']},
            {'state': 'maryland', 'abbreviation': 'md', 'capital': 'annapolis', 'population': 4217.0e+3, 'area': 10460, 'index': 7, 'cities': ['baltimore', 'silver spring', 'dundalk', 'bethesda']},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'capital': 'boston', 'population': 5737.0e+3, 'area': 8284, 'index': 6, 'cities': ['boston', 'worcester', 'springfield', 'new bedford']},
            {'state': 'michigan', 'abbreviation': 'mi', 'capital': 'lansing', 'population': 9262.0e+3, 'area': 58.5e+3, 'index': 26, 'cities': ['detroit', 'grand rapids', 'warren', 'flint']},
            {'state': 'minnesota', 'abbreviation': 'mn', 'capital': 'st. paul', 'population': 4076.0e+3, 'area': 84.4e+3, 'index': 32, 'cities': ['minneapolis', 'st. paul', 'duluth', 'bloomington']},
            {'state': 'mississippi', 'abbreviation': 'ms', 'capital': 'jackson', 'population': 2520.0e+3, 'area': 47.7e+3, 'index': 20, 'cities': ['jackson', 'biloxi', 'meridian', 'hattiesburg']},
            {'state': 'missouri', 'abbreviation': 'mo', 'capital': 'jefferson city', 'population': 4916.0e+3, 'area': 69.7e+3, 'index': 24, 'cities': ['st. louis', 'kansas city', 'springfield', 'independence']},
            {'state': 'montana', 'abbreviation': 'mt', 'capital': 'helena', 'population': 786.7e+3, 'area': 147.0e+3, 'index': 41, 'cities': ['billings', 'great falls', 'butte', 'missoula']},
            {'state': 'nebraska', 'abbreviation': 'ne', 'capital': 'lincoln', 'population': 1569.0e+3, 'area': 77.3e+3, 'index': 37, 'cities': ['omaha', 'lincoln', 'grand island', 'north platte']},
            {'state': 'nevada', 'abbreviation': 'nv', 'capital': 'carson city', 'population': 800.5e+3, 'area': 110.5e+3, 'index': 36, 'cities': ['las vegas', 'reno', 'sunrise manor', 'sparks']},
            {'state': 'new hampshire', 'abbreviation': 'nh', 'capital': 'concord', 'population': 920.6e+3, 'area': 9279, 'index': 9, 'cities': ['manchester', 'nashua', 'concord', 'portsmouth']},
            {'state': 'new jersey', 'abbreviation': 'nj', 'capital': 'trenton', 'population': 7365.0e+3, 'area': 7787, 'index': 3, 'cities': ['newark', 'jersey city', 'paterson', 'elizabeth']},
            {'state': 'new mexico', 'abbreviation': 'nm', 'capital': 'santa fe', 'population': 1303.0e+3, 'area': 121.6e+3, 'index': 47, 'cities': ['albuquerque', 'santa fe', 'las cruces', 'roswell']},
            {'state': 'new york', 'abbreviation': 'ny', 'capital': 'albany', 'population': 17.558e+6, 'area': 49.1e+3, 'index': 11, 'cities': ['new york', 'buffalo', 'rochester', 'yonkers']},
            {'state': 'north carolina', 'abbreviation': 'nc', 'capital': 'raleigh', 'population': 5882.0e+3, 'area': 52.67e+3, 'index': 12, 'cities': ['charlotte', 'greensboro', 'raleigh', 'winston-salem']},
            {'state': 'north dakota', 'abbreviation': 'nd', 'capital': 'bismarck', 'population': 652.7e+3, 'area': 70.7e+3, 'index': 39, 'cities': ['fargo', 'bismarck', 'grand forks', 'minot']},
            {'state': 'ohio', 'abbreviation': 'oh', 'capital': 'columbus', 'population': 10.8e+6, 'area': 41.3e+3, 'index': 17, 'cities': ['cleveland', 'columbus', 'cincinnati', 'toledo']},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'capital': 'oklahoma city', 'population': 3025.0e+3, 'area': 69.95e+3, 'index': 46, 'cities': ['oklahoma city', 'tulsa', 'lawton', 'norman']},
            {'state': 'oregon', 'abbreviation': 'or', 'capital': 'salem', 'population': 2633.0e+3, 'area': 97073, 'index': 33, 'cities': ['portland', 'eugene', 'salem', 'springfield']},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'capital': 'harrisburg', 'population': 11.863e+6, 'area': 45308, 'index': 2, 'cities': ['philadelphia', 'pittsburgh', 'erie', 'allentown']},
            {'state': 'rhode island', 'abbreviation': 'ri', 'capital': 'providence', 'population': 947.2e+3, 'area': 1212, 'index': 13, 'cities': ['providence', 'warwick', 'cranston', 'pawtucket']},
            {'state': 'south carolina', 'abbreviation': 'sc', 'capital': 'columbia', 'population': 3121.8e+3, 'area': 31.113e+3, 'index': 8, 'cities': ['columbia', 'charleston', 'north charleston', 'greenville']},
            {'state': 'south dakota', 'abbreviation': 'sd', 'capital': 'pierre', 'population': 690.767e+3, 'area': 77116, 'index': 40, 'cities': ['sioux falls', 'rapid city', 'aberdeen', 'watertown']},
            {'state': 'tennessee', 'abbreviation': 'tn', 'capital': 'nashville', 'population': 4591.0e+3, 'area': 42.14e+3, 'index': 16, 'cities': ['memphis', 'nashville', 'knoxville', 'chattanooga']},
            {'state': 'texas', 'abbreviation': 'tx', 'capital': 'austin', 'population': 14.229e+6, 'area': 266.807e+3, 'index': 28, 'cities': ['houston', 'dallas', 'san antonio', 'el paso']},
            {'state': 'utah', 'abbreviation': 'ut', 'capital': 'salt lake city', 'population': 1461.0e+3, 'area': 84.9e+3, 'index': 45, 'cities': ['salt lake city', 'provo', 'west valley', 'ogden']},
            {'state': 'vermont', 'abbreviation': 'vt', 'capital': 'montpelier', 'population': 511.5e+3, 'area': 9614, 'index': 14, 'cities': ['burlington', 'rutland', 'bennington', 'essex']},
            {'state': 'virginia', 'abbreviation': 'va', 'capital': 'richmond', 'population': 5346.8e+3, 'area': 40.76e+3, 'index': 10, 'cities': ['norfolk', 'virginia beach', 'richmond', 'arlington']},
            {'state': 'washington', 'abbreviation': 'wa', 'capital': 'olympia', 'population': 41.132e+5, 'area': 68.139e+3, 'index': 42, 'cities': ['seattle', 'spokane', 'tacoma', 'bellevue']},
            {'state': 'west virginia', 'abbreviation': 'wv', 'capital': 'charleston', 'population': 1.95e+6, 'area': 24.2e+3, 'index': 35, 'cities': ['charleston', 'huntington', 'wheeling', 'parkersburg']},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'capital': 'madison', 'population': 4.7e+6, 'area': 56153, 'index': 30, 'cities': ['milwaukee', 'madison', 'green bay', 'racine']},
            {'state': 'wyoming', 'abbreviation': 'wy', 'capital': 'cheyenne', 'population': 469.557e+3, 'area': 97.809e+3, 'index': 44, 'cities': ['casper', 'cheyenne', 'laramie', 'rock springs']},
        ]

cities = [  {'state': 'alabama', 'abbreviation': 'al', 'city': 'birmingham', 'population': 284413},
            {'state': 'alabama', 'abbreviation': 'al', 'city': 'mobile', 'population': 200452},
            {'state': 'alabama', 'abbreviation': 'al', 'city': 'montgomery', 'population': 177857},
            {'state': 'alabama', 'abbreviation': 'al', 'city': 'huntsville', 'population': 142513},
            {'state': 'alabama', 'abbreviation': 'al', 'city': 'tuscaloosa', 'population': 75143},
            {'state': 'alaska', 'abbreviation': 'ak', 'city': 'anchorage', 'population': 174431},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'phoenix', 'population': 789704},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'tucson', 'population': 330537},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'mesa', 'population': 152453},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'tempe', 'population': 106919},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'glendale', 'population': 96988},
            {'state': 'arizona', 'abbreviation': 'az', 'city': 'scottsdale', 'population': 88622},
            {'state': 'arkansas', 'abbreviation': 'ar', 'city': 'little rock', 'population': 158915},
            {'state': 'arkansas', 'abbreviation': 'ar', 'city': 'fort smith', 'population': 71384},
            {'state': 'arkansas', 'abbreviation': 'ar', 'city': 'north little rock', 'population': 64388},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'los angeles', 'population': 2966850},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san diego', 'population': 875538},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san francisco', 'population': 678974},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san jose', 'population': 629442},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'long beach', 'population': 361334},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'oakland', 'population': 339337},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'sacramento', 'population': 275741},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'anaheim', 'population': 219311},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'fresno', 'population': 218202},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'santa ana', 'population': 203713},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'riverside', 'population': 170876},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'huntington beach', 'population': 170505},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'stockton', 'population': 149779},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'glendale', 'population': 139060},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'fremont', 'population': 131945},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'torrance', 'population': 131497},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'garden grove', 'population': 123351},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san bernardino', 'population': 118794},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'pasadena', 'population': 118072},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'east los angeles', 'population': 110017},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'oxnard', 'population': 108195},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'modesto', 'population': 106963},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'sunnyvale', 'population': 106618},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'bakersfield', 'population': 105611},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'concord', 'population': 103763},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'berkeley', 'population': 103328},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'fullerton', 'population': 102246},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'inglewood', 'population': 94162},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'hayward', 'population': 93585},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'pomona', 'population': 92742},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'orange', 'population': 91450},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'ontario', 'population': 88820},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'santa monica', 'population': 88314},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'santa clara', 'population': 87700},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'citrus heights', 'population': 85911},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'norwalk', 'population': 84901},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'burbank', 'population': 84625},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'chula vista', 'population': 83927},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'santa rosa', 'population': 83205},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'downey', 'population': 82602},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'costa mesa', 'population': 82291},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'compton', 'population': 81230},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'carson', 'population': 81221},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'salinas', 'population': 80479},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'west covina', 'population': 80292},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'vallejo', 'population': 80188},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'el monte', 'population': 79494},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'daly city', 'population': 78519},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'thousand oaks', 'population': 77797},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san mateo', 'population': 77640},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'simi valley', 'population': 77500},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'oceanside', 'population': 76698},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'richmond', 'population': 74676},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'lakewood', 'population': 74654},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'santa barbara', 'population': 74542},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'el cajon', 'population': 73892},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'ventura', 'population': 73774},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'westminster', 'population': 71133},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'whittier', 'population': 68558},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'south gate', 'population': 66784},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'alhambra', 'population': 64767},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'buena park', 'population': 64165},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'san leandro', 'population': 63952},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'alameda', 'population': 63852},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'newport beach', 'population': 63475},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'escondido', 'population': 62480},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'irvine', 'population': 62134},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'mountain view', 'population': 58655},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'fairfield', 'population': 58099},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'redondo beach', 'population': 57102},
            {'state': 'california', 'abbreviation': 'ca', 'city': 'scotts valley', 'population': 6037},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'denver', 'population': 492365},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'colorado springs', 'population': 215150},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'aurora', 'population': 158588},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'lakewood', 'population': 113808},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'pueblo', 'population': 101686},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'arvada', 'population': 84576},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'boulder', 'population': 76685},
            {'state': 'colorado', 'abbreviation': 'co', 'city': 'fort collins', 'population': 64632},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'bridgeport', 'population': 142546},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'hartford', 'population': 136392},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'new haven', 'population': 126089},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'waterbury', 'population': 103266},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'stamford', 'population': 102466},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'norwalk', 'population': 77767},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'new britain', 'population': 73840},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'west hartford', 'population': 61301},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'danbury', 'population': 60470},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'greenwich', 'population': 59578},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'bristol', 'population': 57370},
            {'state': 'connecticut', 'abbreviation': 'ct', 'city': 'meriden', 'population': 57118},
            {'state': 'delaware', 'abbreviation': 'de', 'city': 'wilmington', 'population': 70195},
            {'state': 'district of columbia', 'abbreviation': 'dc', 'city': 'washington', 'population': 638333},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'jacksonville', 'population': 540920},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'miami', 'population': 346865},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'tampa', 'population': 271523},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'st. petersburg', 'population': 238647},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'fort lauderdale', 'population': 153256},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'orlando', 'population': 128394},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'hollywood', 'population': 117188},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'miami beach', 'population': 96298},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'clearwater', 'population': 85450},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'tallahassee', 'population': 81548},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'gainesville', 'population': 81371},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'kendall', 'population': 73758},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'west palm beach', 'population': 62530},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'largo', 'population': 58977},
            {'state': 'florida', 'abbreviation': 'fl', 'city': 'pensacola', 'population': 57619},
            {'state': 'georgia', 'abbreviation': 'ga', 'city': 'atlanta', 'population': 425022},
            {'state': 'georgia', 'abbreviation': 'ga', 'city': 'columbus', 'population': 169441},
            {'state': 'georgia', 'abbreviation': 'ga', 'city': 'savannah', 'population': 141654},
            {'state': 'georgia', 'abbreviation': 'ga', 'city': 'macon', 'population': 116860},
            {'state': 'georgia', 'abbreviation': 'ga', 'city': 'albany', 'population': 74425},
            {'state': 'hawaii', 'abbreviation': 'hi', 'city': 'honolulu', 'population': 762874},
            {'state': 'hawaii', 'abbreviation': 'hi', 'city': 'ewa', 'population': 190037},
            {'state': 'hawaii', 'abbreviation': 'hi', 'city': 'koolaupoko', 'population': 109373},
            {'state': 'idaho', 'abbreviation': 'id', 'city': 'boise', 'population': 102249},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'chicago', 'population': 3005172},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'rockford', 'population': 139712},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'peoria', 'population': 124160},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'springfield', 'population': 100054},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'decatur', 'population': 93939},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'aurora', 'population': 81293},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'joliet', 'population': 77956},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'evanston', 'population': 73706},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'waukegan', 'population': 67653},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'arlington heights', 'population': 66116},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'elgin', 'population': 63668},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'cicero', 'population': 61232},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'oak lawn', 'population': 60590},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'skokie', 'population': 60278},
            {'state': 'illinois', 'abbreviation': 'il', 'city': 'champaign', 'population': 58267},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'indianapolis', 'population': 700807},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'fort wayne', 'population': 172196},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'gary', 'population': 151968},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'evansville', 'population': 130496},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'south bend', 'population': 109727},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'hammond', 'population': 93714},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'muncie', 'population': 77216},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'anderson', 'population': 64695},
            {'state': 'indiana', 'abbreviation': 'in', 'city': 'terre haute', 'population': 61125},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'des moines', 'population': 191003},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'cedar rapids', 'population': 110243},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'davenport', 'population': 103254},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'sioux city', 'population': 82003},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'waterloo', 'population': 75985},
            {'state': 'iowa', 'abbreviation': 'ia', 'city': 'dubuque', 'population': 62321},
            {'state': 'kansas', 'abbreviation': 'ks', 'city': 'wichita', 'population': 279212},
            {'state': 'kansas', 'abbreviation': 'ks', 'city': 'kansas city', 'population': 161148},
            {'state': 'kansas', 'abbreviation': 'ks', 'city': 'topeka', 'population': 118690},
            {'state': 'kansas', 'abbreviation': 'ks', 'city': 'overland park', 'population': 81784},
            {'state': 'kentucky', 'abbreviation': 'ky', 'city': 'louisville', 'population': 298451},
            {'state': 'kentucky', 'abbreviation': 'ky', 'city': 'lexington', 'population': 204165},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'new orleans', 'population': 557515},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'baton rouge', 'population': 219419},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'shreveport', 'population': 205820},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'metairie', 'population': 164160},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'lafayette', 'population': 80584},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'lake charles', 'population': 75051},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'kenner', 'population': 66382},
            {'state': 'louisiana', 'abbreviation': 'la', 'city': 'monroe', 'population': 57597},
            {'state': 'maine', 'abbreviation': 'me', 'city': 'portland', 'population': 61572},
            {'state': 'maryland', 'abbreviation': 'md', 'city': 'baltimore', 'population': 786775},
            {'state': 'maryland', 'abbreviation': 'md', 'city': 'silver spring', 'population': 72893},
            {'state': 'maryland', 'abbreviation': 'md', 'city': 'dundalk', 'population': 71293},
            {'state': 'maryland', 'abbreviation': 'md', 'city': 'bethesda', 'population': 63022},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'boston', 'population': 562994},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'worcester', 'population': 161799},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'springfield', 'population': 152319},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'new bedford', 'population': 98478},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'cambridge', 'population': 95322},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'brockton', 'population': 95172},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'fall river', 'population': 92574},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'lowell', 'population': 92418},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'quincy', 'population': 84743},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'newton', 'population': 83622},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'lynn', 'population': 78471},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'somerville', 'population': 77372},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'framingham', 'population': 65113},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'lawrence', 'population': 63175},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'waltham', 'population': 58200},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'city': 'medford', 'population': 58076},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'detroit', 'population': 1203339},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'grand rapids', 'population': 181843},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'warren', 'population': 161134},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'flint', 'population': 159611},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'lansing', 'population': 130414},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'sterling heights', 'population': 108999},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'ann arbor', 'population': 107969},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'livonia', 'population': 104814},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'dearborn', 'population': 90660},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'westland', 'population': 84603},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'kalamazoo', 'population': 79722},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'taylor', 'population': 77568},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'saginaw', 'population': 77508},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'pontiac', 'population': 76715},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'st. clair shores', 'population': 76210},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'southfield', 'population': 75568},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'clinton', 'population': 72400},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'royal oak', 'population': 70893},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'dearborn heights', 'population': 67706},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'troy', 'population': 67102},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'waterford', 'population': 64250},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'wyoming', 'population': 59616},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'redford', 'population': 58441},
            {'state': 'michigan', 'abbreviation': 'mi', 'city': 'farmington hills', 'population': 58056},
            {'state': 'minnesota', 'abbreviation': 'mn', 'city': 'minneapolis', 'population': 370951},
            {'state': 'minnesota', 'abbreviation': 'mn', 'city': 'st. paul', 'population': 270230},
            {'state': 'minnesota', 'abbreviation': 'mn', 'city': 'duluth', 'population': 92811},
            {'state': 'minnesota', 'abbreviation': 'mn', 'city': 'bloomington', 'population': 81831},
            {'state': 'minnesota', 'abbreviation': 'mn', 'city': 'rochester', 'population': 57906},
            {'state': 'mississippi', 'abbreviation': 'ms', 'city': 'jackson', 'population': 202895},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'st. louis', 'population': 453085},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'kansas city', 'population': 448159},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'springfield', 'population': 133116},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'independence', 'population': 111797},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'st. joseph', 'population': 76691},
            {'state': 'missouri', 'abbreviation': 'mo', 'city': 'columbia', 'population': 62061},
            {'state': 'montana', 'abbreviation': 'mt', 'city': 'billings', 'population': 66842},
            {'state': 'montana', 'abbreviation': 'mt', 'city': 'great falls', 'population': 56725},
            {'state': 'nebraska', 'abbreviation': 'ne', 'city': 'omaha', 'population': 314255},
            {'state': 'nebraska', 'abbreviation': 'ne', 'city': 'lincoln', 'population': 171932},
            {'state': 'nevada', 'abbreviation': 'nv', 'city': 'las vegas', 'population': 164674},
            {'state': 'nevada', 'abbreviation': 'nv', 'city': 'reno', 'population': 100756},
            {'state': 'new hampshire', 'abbreviation': 'nh', 'city': 'manchester', 'population': 90936},
            {'state': 'new hampshire', 'abbreviation': 'nh', 'city': 'nashua', 'population': 67865},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'newark', 'population': 329248},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'jersey city', 'population': 223532},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'paterson', 'population': 137970},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'elizabeth', 'population': 106201},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'trenton', 'population': 92124},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'woodbridge', 'population': 90074},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'camden', 'population': 84910},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'east orange', 'population': 77878},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'clifton', 'population': 74388},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'edison', 'population': 70193},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'cherry hill', 'population': 68785},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'bayonne', 'population': 65047},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'middletown', 'population': 61615},
            {'state': 'new jersey', 'abbreviation': 'nj', 'city': 'irvington', 'population': 61493},
            {'state': 'new mexico', 'abbreviation': 'nm', 'city': 'albuquerque', 'population': 331767},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'new york', 'population': 7071639},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'buffalo', 'population': 357870},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'rochester', 'population': 241741},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'yonkers', 'population': 195351},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'syracuse', 'population': 170105},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'albany', 'population': 101727},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'cheektowaga', 'population': 92145},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'utica', 'population': 75632},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'niagara falls', 'population': 71384},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'new rochelle', 'population': 70794},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'schenectady', 'population': 67972},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'mount vernon', 'population': 66713},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'irondequoit', 'population': 57648},
            {'state': 'new york', 'abbreviation': 'ny', 'city': 'levittown', 'population': 57045},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'charlotte', 'population': 314447},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'greensboro', 'population': 155642},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'raleigh', 'population': 149771},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'winston-salem', 'population': 131885},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'durham', 'population': 100538},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'high point', 'population': 64107},
            {'state': 'north carolina', 'abbreviation': 'nc', 'city': 'fayetteville', 'population': 59507},
            {'state': 'north dakota', 'abbreviation': 'nd', 'city': 'fargo', 'population': 61308},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'cleveland', 'population': 573822},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'columbus', 'population': 564871},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'cincinnati', 'population': 385457},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'toledo', 'population': 354635},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'akron', 'population': 237177},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'dayton', 'population': 203371},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'youngstown', 'population': 115436},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'canton', 'population': 93077},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'parma', 'population': 92548},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'lorain', 'population': 75416},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'springfield', 'population': 72563},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'hamilton', 'population': 63189},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'lakewood', 'population': 61963},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'kettering', 'population': 61186},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'euclid', 'population': 59999},
            {'state': 'ohio', 'abbreviation': 'oh', 'city': 'elyria', 'population': 57504},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'city': 'oklahoma city', 'population': 403213},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'city': 'tulsa', 'population': 360919},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'city': 'lawton', 'population': 80054},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'city': 'norman', 'population': 68020},
            {'state': 'oregon', 'abbreviation': 'or', 'city': 'portland', 'population': 366383},
            {'state': 'oregon', 'abbreviation': 'or', 'city': 'eugene', 'population': 105664},
            {'state': 'oregon', 'abbreviation': 'or', 'city': 'salem', 'population': 89233},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'philadelphia', 'population': 1688210},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'pittsburgh', 'population': 423938},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'erie', 'population': 119123},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'allentown', 'population': 103758},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'scranton', 'population': 88117},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'upper darby', 'population': 84054},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'reading', 'population': 78686},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'bethlehem', 'population': 70419},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'lower merion', 'population': 59651},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'abingdon', 'population': 59084},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'bristol township', 'population': 58733},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'penn hills', 'population': 57632},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'city': 'altoona', 'population': 57078},
            {'state': 'rhode island', 'abbreviation': 'ri', 'city': 'providence', 'population': 156804},
            {'state': 'rhode island', 'abbreviation': 'ri', 'city': 'warwick', 'population': 87123},
            {'state': 'rhode island', 'abbreviation': 'ri', 'city': 'cranston', 'population': 71992},
            {'state': 'rhode island', 'abbreviation': 'ri', 'city': 'pawtucket', 'population': 71204},
            {'state': 'south carolina', 'abbreviation': 'sc', 'city': 'columbia', 'population': 101229},
            {'state': 'south carolina', 'abbreviation': 'sc', 'city': 'charleston', 'population': 69855},
            {'state': 'south carolina', 'abbreviation': 'sc', 'city': 'north charleston', 'population': 62504},
            {'state': 'south carolina', 'abbreviation': 'sc', 'city': 'greenville', 'population': 58242},
            {'state': 'south dakota', 'abbreviation': 'sd', 'city': 'sioux falls', 'population': 81343},
            {'state': 'tennessee', 'abbreviation': 'tn', 'city': 'memphis', 'population': 646356},
            {'state': 'tennessee', 'abbreviation': 'tn', 'city': 'nashville', 'population': 455651},
            {'state': 'tennessee', 'abbreviation': 'tn', 'city': 'knoxville', 'population': 175030},
            {'state': 'tennessee', 'abbreviation': 'tn', 'city': 'chattanooga', 'population': 169728},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'houston', 'population': 1595138},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'dallas', 'population': 904078},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'san antonio', 'population': 785880},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'el paso', 'population': 425259},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'fort worth', 'population': 385164},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'austin', 'population': 345496},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'corpus christi', 'population': 231999},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'lubbock', 'population': 173979},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'arlington', 'population': 160123},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'amarillo', 'population': 149230},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'garland', 'population': 138857},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'beaumont', 'population': 118102},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'pasadena', 'population': 112560},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'irving', 'population': 109943},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'waco', 'population': 101261},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'abilene', 'population': 98315},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'wichita falls', 'population': 94201},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'laredo', 'population': 91449},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'odessa', 'population': 90027},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'brownsville', 'population': 84997},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'san angelo', 'population': 73240},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'richardson', 'population': 72496},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'plano', 'population': 72331},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'grand prairie', 'population': 71462},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'midland', 'population': 70525},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'tyler', 'population': 70508},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'mesquite', 'population': 67053},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'mcallen', 'population': 67042},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'longview', 'population': 62762},
            {'state': 'texas', 'abbreviation': 'tx', 'city': 'port arthur', 'population': 61195},
            {'state': 'utah', 'abbreviation': 'ut', 'city': 'salt lake city', 'population': 163034},
            {'state': 'utah', 'abbreviation': 'ut', 'city': 'provo', 'population': 74111},
            {'state': 'utah', 'abbreviation': 'ut', 'city': 'west valley', 'population': 72299},
            {'state': 'utah', 'abbreviation': 'ut', 'city': 'ogden', 'population': 64407},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'norfolk', 'population': 266979},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'virginia beach', 'population': 262199},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'richmond', 'population': 219214},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'arlington', 'population': 152599},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'newport news', 'population': 144903},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'hampton', 'population': 122617},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'chesapeake', 'population': 114226},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'portsmouth', 'population': 104577},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'alexandria', 'population': 103217},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'roanoke', 'population': 100427},
            {'state': 'virginia', 'abbreviation': 'va', 'city': 'lynchburg', 'population': 66743},
            {'state': 'washington', 'abbreviation': 'wa', 'city': 'seattle', 'population': 493846},
            {'state': 'washington', 'abbreviation': 'wa', 'city': 'spokane', 'population': 171300},
            {'state': 'washington', 'abbreviation': 'wa', 'city': 'tacoma', 'population': 158501},
            {'state': 'washington', 'abbreviation': 'wa', 'city': 'bellevue', 'population': 73903},
            {'state': 'west virginia', 'abbreviation': 'wv', 'city': 'charleston', 'population': 63968},
            {'state': 'west virginia', 'abbreviation': 'wv', 'city': 'huntington', 'population': 63684},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'milwaukee', 'population': 636212},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'madison', 'population': 170616},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'green bay', 'population': 87899},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'racine', 'population': 85725},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'kenosha', 'population': 77685},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'west allis', 'population': 63982},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'city': 'appleton', 'population': 58913},
            {'state': 'wyoming', 'abbreviation': 'wy', 'city': 'casper', 'population': 51016},
        ]

rivers = [  {'river': 'mississippi', 'length': 3778, 'states': ['minnesota', 'wisconsin', 'iowa', 'illinois', 'missouri', 'kentucky', 'tennessee', 'arkansas', 'mississippi', 'louisiana', 'louisiana']},
            {'river': 'missouri', 'length': 3968, 'states': ['montana', 'north dakota', 'south dakota', 'iowa', 'nebraska', 'missouri', 'missouri']},
            {'river': 'colorado', 'length': 2333, 'states': ['colorado', 'utah', 'arizona', 'nevada', 'california']},
            {'river': 'ohio', 'length': 1569, 'states': ['pennsylvania', 'west virginia', 'kentucky', 'indiana', 'illinois', 'illinois', 'ohio']},
            {'river': 'red', 'length': 1638, 'states': ['new mexico', 'texas', 'oklahoma', 'arkansas', 'arkansas', 'louisiana']},
            {'river': 'arkansas', 'length': 2333, 'states': ['colorado', 'kansas', 'oklahoma', 'arkansas']},
            {'river': 'canadian', 'length': 1458, 'states': ['colorado', 'new mexico', 'texas', 'oklahoma']},
            {'river': 'connecticut', 'length': 655, 'states': ['new hampshire', 'vermont', 'massachusetts', 'connecticut']},
            {'river': 'delaware', 'length': 451, 'states': ['new york', 'pennsylvania', 'new jersey', 'delaware']},
            {'river': 'little missouri', 'length': 901, 'states': ['wyoming', 'montana', 'south dakota', 'north dakota']},
            {'river': 'snake', 'length': 1670, 'states': ['wyoming', 'idaho', 'oregon', 'washington', 'washington']},
            {'river': 'chattahoochee', 'length': 702, 'states': ['georgia', 'georgia', 'florida']},
            {'river': 'cimarron', 'length': 965, 'states': ['new mexico', 'kansas', 'oklahoma']},
            {'river': 'green', 'length': 1175, 'states': ['wyoming', 'utah', 'colorado', 'utah']},
            {'river': 'north platte', 'length': 1094, 'states': ['colorado', 'wyoming', 'nebraska']},
            {'river': 'potomac', 'length': 462, 'states': ['west virginia', 'maryland', 'virginia', 'district of columbia']},
            {'river': 'republican', 'length': 679, 'states': ['colorado', 'nebraska', 'kansas']},
            {'river': 'rio grande', 'length': 3033, 'states': ['colorado', 'new mexico', 'texas']},
            {'river': 'san juan', 'length': 579, 'states': ['colorado', 'new mexico', 'colorado', 'utah']},
            {'river': 'tennessee', 'length': 1049, 'states': ['tennessee', 'alabama', 'tennessee', 'kentucky']},
            {'river': 'wabash', 'length': 764, 'states': ['ohio', 'indiana', 'illinois']},
            {'river': 'yellowstone', 'length': 1080, 'states': ['wyoming', 'montana', 'north dakota']},
            {'river': 'allegheny', 'length': 523, 'states': ['pennsylvania', 'new york', 'pennsylvania']},
            {'river': 'bighorn', 'length': 541, 'states': ['wyoming', 'montana']},
            {'river': 'cheyenne', 'length': 848, 'states': ['wyoming', 'north dakota']},
            {'river': 'clark fork', 'length': 483, 'states': ['montana', 'idaho']},
            {'river': 'columbia', 'length': 1953, 'states': ['washington', 'oregon']},
            {'river': 'cumberland', 'length': 1105, 'states': ['kentucky', 'tennessee', 'kentucky']},
            {'river': 'dakota', 'length': 1142, 'states': ['north dakota', 'south dakota']},
            {'river': 'gila', 'length': 805, 'states': ['new mexico', 'arizona']},
            {'river': 'hudson', 'length': 492, 'states': ['new york', 'new jersey']},
            {'river': 'neosho', 'length': 740, 'states': ['kansas', 'oklahoma']},
            {'river': 'niobrara', 'length': 693, 'states': ['wyoming', 'nebraska']},
            {'river': 'ouachita', 'length': 973, 'states': ['arkansas', 'louisiana']},
            {'river': 'pearl', 'length': 788, 'states': ['michigan', 'louisiana']},
            {'river': 'pecos', 'length': 805, 'states': ['new mexico', 'texas']},
            {'river': 'powder', 'length': 603, 'states': ['wyoming', 'montana']},
            {'river': 'roanoke', 'length': 660, 'states': ['virginia', 'north carolina']},
            {'river': 'rock', 'length': 459, 'states': ['wisconsin', 'illinois']},
            {'river': 'smoky hill', 'length': 869, 'states': ['colorado', 'kansas']},
            {'river': 'south platte', 'length': 682, 'states': ['colorado', 'nebraska']},
            {'river': 'st. francis', 'length': 684, 'states': ['missouri', 'arkansas']},
            {'river': 'tombigbee', 'length': 658, 'states': ['mississippi', 'alabama']},
            {'river': 'washita', 'length': 805, 'states': ['texas', 'oklahoma']},
            {'river': 'wateree catawba', 'length': 636, 'states': ['north carolina', 'south carolina']},
            {'river': 'white', 'length': 1110, 'states': ['arkansas', 'missouri', 'arkansas']},
        ]

borders = [ {'state': 'alabama', 'abbreviation': 'al', 'neighbors': ['tennessee', 'georgia', 'florida', 'mississippi']},
            {'state': 'alaska', 'abbreviation': 'ak', 'neighbors': []},
            {'state': 'arizona', 'abbreviation': 'az', 'neighbors': ['utah', 'colorado', 'new mexico', 'california', 'nevada']},
            {'state': 'arkansas', 'abbreviation': 'ar', 'neighbors': ['missouri', 'tennessee', 'mississippi', 'louisiana', 'texas', 'oklahoma']},
            {'state': 'california', 'abbreviation': 'ca', 'neighbors': ['oregon', 'nevada', 'arizona']},
            {'state': 'colorado', 'abbreviation': 'co', 'neighbors': ['nebraska', 'kansas', 'oklahoma', 'new mexico', 'arizona', 'utah', 'wyoming']},
            {'state': 'connecticut', 'abbreviation': 'ct', 'neighbors': ['massachusetts', 'rhode island', 'new york']},
            {'state': 'delaware', 'abbreviation': 'de', 'neighbors': ['pennsylvania', 'new jersey', 'maryland']},
            {'state': 'district of columbia', 'abbreviation': 'dc', 'neighbors': ['maryland', 'virginia']},
            {'state': 'florida', 'abbreviation': 'fl', 'neighbors': ['georgia', 'alabama']},
            {'state': 'georgia', 'abbreviation': 'ga', 'neighbors': ['north carolina', 'south carolina', 'florida', 'alabama', 'tennessee']},
            {'state': 'hawaii', 'abbreviation': 'hi', 'neighbors': []},
            {'state': 'idaho', 'abbreviation': 'id', 'neighbors': ['montana', 'wyoming', 'utah', 'nevada', 'oregon', 'washington']},
            {'state': 'illinois', 'abbreviation': 'il', 'neighbors': ['wisconsin', 'indiana', 'kentucky', 'missouri', 'iowa']},
            {'state': 'indiana', 'abbreviation': 'in', 'neighbors': ['michigan', 'ohio', 'kentucky', 'illinois']},
            {'state': 'iowa', 'abbreviation': 'ia', 'neighbors': ['minnesota', 'wisconsin', 'illinois', 'missouri', 'nebraska', 'south dakota']},
            {'state': 'kansas', 'abbreviation': 'ks', 'neighbors': ['nebraska', 'missouri', 'oklahoma', 'colorado']},
            {'state': 'kentucky', 'abbreviation': 'ky', 'neighbors': ['indiana', 'ohio', 'west virginia', 'virginia', 'tennessee', 'missouri', 'illinois']},
            {'state': 'louisiana', 'abbreviation': 'la', 'neighbors': ['arkansas', 'mississippi', 'texas']},
            {'state': 'maine', 'abbreviation': 'me', 'neighbors': ['new hampshire']},
            {'state': 'maryland', 'abbreviation': 'md', 'neighbors': ['pennsylvania', 'delaware', 'virginia', 'district of columbia', 'west virginia']},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'neighbors': ['new hampshire', 'rhode island', 'connecticut', 'new york', 'vermont']},
            {'state': 'michigan', 'abbreviation': 'mi', 'neighbors': ['ohio', 'indiana', 'wisconsin']},
            {'state': 'minnesota', 'abbreviation': 'mn', 'neighbors': ['wisconsin', 'iowa', 'south dakota', 'north dakota']},
            {'state': 'mississippi', 'abbreviation': 'ms', 'neighbors': ['tennessee', 'alabama', 'louisiana', 'arkansas']},
            {'state': 'missouri', 'abbreviation': 'mo', 'neighbors': ['iowa', 'illinois', 'kentucky', 'tennessee', 'arkansas', 'oklahoma', 'kansas', 'nebraska']},
            {'state': 'montana', 'abbreviation': 'mt', 'neighbors': ['north dakota', 'south dakota', 'wyoming', 'idaho']},
            {'state': 'nebraska', 'abbreviation': 'ne', 'neighbors': ['south dakota', 'iowa', 'missouri', 'kansas', 'colorado', 'wyoming']},
            {'state': 'nevada', 'abbreviation': 'nv', 'neighbors': ['idaho', 'utah', 'arizona', 'california', 'oregon']},
            {'state': 'new hampshire', 'abbreviation': 'nh', 'neighbors': ['maine', 'massachusetts', 'vermont']},
            {'state': 'new jersey', 'abbreviation': 'nj', 'neighbors': ['new york', 'delaware', 'pennsylvania']},
            {'state': 'new mexico', 'abbreviation': 'nm', 'neighbors': ['colorado', 'oklahoma', 'texas', 'arizona', 'utah']},
            {'state': 'new york', 'abbreviation': 'ny', 'neighbors': ['vermont', 'massachusetts', 'connecticut', 'new jersey', 'pennsylvania']},
            {'state': 'north carolina', 'abbreviation': 'nc', 'neighbors': ['virginia', 'south carolina', 'georgia', 'tennessee']},
            {'state': 'north dakota', 'abbreviation': 'nd', 'neighbors': ['minnesota', 'south dakota', 'montana']},
            {'state': 'ohio', 'abbreviation': 'oh', 'neighbors': ['michigan', 'pennsylvania', 'west virginia', 'kentucky', 'indiana']},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'neighbors': ['kansas', 'missouri', 'arkansas', 'texas', 'new mexico', 'colorado']},
            {'state': 'oregon', 'abbreviation': 'or', 'neighbors': ['washington', 'idaho', 'nevada', 'california']},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'neighbors': ['new york', 'new jersey', 'delaware', 'maryland', 'west virginia', 'ohio']},
            {'state': 'rhode island', 'abbreviation': 'ri', 'neighbors': ['massachusetts', 'connecticut']},
            {'state': 'south carolina', 'abbreviation': 'sc', 'neighbors': ['north carolina', 'georgia']},
            {'state': 'south dakota', 'abbreviation': 'sd', 'neighbors': ['north dakota', 'minnesota', 'iowa', 'nebraska', 'wyoming', 'montana']},
            {'state': 'tennessee', 'abbreviation': 'tn', 'neighbors': ['kentucky', 'virginia', 'north carolina', 'georgia', 'alabama', 'mississippi', 'arkansas', 'missouri']},
            {'state': 'texas', 'abbreviation': 'tx', 'neighbors': ['oklahoma', 'arkansas', 'louisiana', 'new mexico']},
            {'state': 'utah', 'abbreviation': 'ut', 'neighbors': ['wyoming', 'colorado', 'new mexico', 'arizona', 'nevada', 'idaho']},
            {'state': 'vermont', 'abbreviation': 'vt', 'neighbors': ['new hampshire', 'massachusetts', 'new york']},
            {'state': 'virginia', 'abbreviation': 'va', 'neighbors': ['maryland', 'district of columbia', 'north carolina', 'tennessee', 'kentucky', 'west virginia']},
            {'state': 'washington', 'abbreviation': 'wa', 'neighbors': ['idaho', 'oregon']},
            {'state': 'west virginia', 'abbreviation': 'wv', 'neighbors': ['pennsylvania', 'maryland', 'virginia', 'kentucky', 'ohio']},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'neighbors': ['michigan', 'illinois', 'iowa', 'minnesota']},
            {'state': 'wyoming', 'abbreviation': 'wy', 'neighbors': ['montana', 'south dakota', 'nebraska', 'colorado', 'utah', 'idaho']},
        ]

highlows = [{'state': 'alabama', 'abbreviation': 'al', 'high_point': 'cheaha mountain', 'high_elevation': 734, 'low_point': 'gulf of mexico', 'low_elevation': 0},
            {'state': 'alaska', 'abbreviation': 'ak', 'high_point': 'mount mckinley', 'high_elevation': 6194, 'low_point': 'pacific ocean', 'low_elevation': 0},
            {'state': 'arizona', 'abbreviation': 'az', 'high_point': 'humphreys peak', 'high_elevation': 3851, 'low_point': 'colorado river', 'low_elevation': 21},
            {'state': 'arkansas', 'abbreviation': 'ar', 'high_point': 'magazine mountain', 'high_elevation': 839, 'low_point': 'ouachita river', 'low_elevation': 17},
            {'state': 'california', 'abbreviation': 'ca', 'high_point': 'mount whitney', 'high_elevation': 4418, 'low_point': 'death valley', 'low_elevation': -85},
            {'state': 'colorado', 'abbreviation': 'co', 'high_point': 'mount elbert', 'high_elevation': 4399, 'low_point': 'arkansas river', 'low_elevation': 1021},
            {'state': 'connecticut', 'abbreviation': 'ct', 'high_point': 'mount frissell', 'high_elevation': 725, 'low_point': 'long island sound', 'low_elevation': 0},
            {'state': 'delaware', 'abbreviation': 'de', 'high_point': 'centerville', 'high_elevation': 135, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'district of columbia', 'abbreviation': 'dc', 'high_point': 'tenleytown', 'high_elevation': 125, 'low_point': 'potomac river', 'low_elevation': 0},
            {'state': 'florida', 'abbreviation': 'fl', 'high_point': 'walton county', 'high_elevation': 105, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'georgia', 'abbreviation': 'ga', 'high_point': 'brasstown bald', 'high_elevation': 1458, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'hawaii', 'abbreviation': 'hi', 'high_point': 'mauna kea', 'high_elevation': 4205, 'low_point': 'pacific ocean', 'low_elevation': 0},
            {'state': 'idaho', 'abbreviation': 'id', 'high_point': 'borah peak', 'high_elevation': 3859, 'low_point': 'snake river', 'low_elevation': 216},
            {'state': 'illinois', 'abbreviation': 'il', 'high_point': 'charles mound', 'high_elevation': 376, 'low_point': 'mississippi river', 'low_elevation': 85},
            {'state': 'indiana', 'abbreviation': 'in', 'high_point': 'franklin township', 'high_elevation': 383, 'low_point': 'ohio river', 'low_elevation': 98},
            {'state': 'iowa', 'abbreviation': 'ia', 'high_point': 'ocheyedan mound', 'high_elevation': 511, 'low_point': 'mississippi river', 'low_elevation': 146},
            {'state': 'kansas', 'abbreviation': 'ks', 'high_point': 'mount sunflower', 'high_elevation': 1231, 'low_point': 'verdigris river', 'low_elevation': 207},
            {'state': 'kentucky', 'abbreviation': 'ky', 'high_point': 'black mountain', 'high_elevation': 1263, 'low_point': 'mississippi river', 'low_elevation': 78},
            {'state': 'louisiana', 'abbreviation': 'la', 'high_point': 'driskill mountain', 'high_elevation': 163, 'low_point': 'new orleans', 'low_elevation': -1},
            {'state': 'maine', 'abbreviation': 'me', 'high_point': 'mount katahdin', 'high_elevation': 1606, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'maryland', 'abbreviation': 'md', 'high_point': 'backbone mountain', 'high_elevation': 1024, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'massachusetts', 'abbreviation': 'ma', 'high_point': 'mount greylock', 'high_elevation': 1064, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'michigan', 'abbreviation': 'mi', 'high_point': 'mount curwood', 'high_elevation': 604, 'low_point': 'lake erie', 'low_elevation': 174},
            {'state': 'minnesota', 'abbreviation': 'mn', 'high_point': 'eagle mountain', 'high_elevation': 701, 'low_point': 'lake superior', 'low_elevation': 183},
            {'state': 'mississippi', 'abbreviation': 'ms', 'high_point': 'woodall mountain', 'high_elevation': 246, 'low_point': 'gulf of mexico', 'low_elevation': 0},
            {'state': 'missouri', 'abbreviation': 'mo', 'high_point': 'taum sauk mountain', 'high_elevation': 540, 'low_point': 'st. francis river', 'low_elevation': 70},
            {'state': 'montana', 'abbreviation': 'mt', 'high_point': 'granite peak', 'high_elevation': 3901, 'low_point': 'kootenai river', 'low_elevation': 549},
            {'state': 'nebraska', 'abbreviation': 'ne', 'high_point': 'johnson township', 'high_elevation': 1654, 'low_point': 'southeast corner', 'low_elevation': 256},
            {'state': 'nevada', 'abbreviation': 'nv', 'high_point': 'boundary peak', 'high_elevation': 4005, 'low_point': 'colorado river', 'low_elevation': 143},
            {'state': 'new hampshire', 'abbreviation': 'nh', 'high_point': 'mount washington', 'high_elevation': 1917, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'new jersey', 'abbreviation': 'nj', 'high_point': 'high point', 'high_elevation': 550, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'new mexico', 'abbreviation': 'nm', 'high_point': 'wheeler peak', 'high_elevation': 4011, 'low_point': 'red bluff reservoir', 'low_elevation': 859},
            {'state': 'new york', 'abbreviation': 'ny', 'high_point': 'mount marcy', 'high_elevation': 1629, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'north carolina', 'abbreviation': 'nc', 'high_point': 'mount mitchell', 'high_elevation': 2037, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'north dakota', 'abbreviation': 'nd', 'high_point': 'white butte', 'high_elevation': 1069, 'low_point': 'red river', 'low_elevation': 229},
            {'state': 'ohio', 'abbreviation': 'oh', 'high_point': 'campbell hill', 'high_elevation': 472, 'low_point': 'ohio river', 'low_elevation': 132},
            {'state': 'oklahoma', 'abbreviation': 'ok', 'high_point': 'black mesa', 'high_elevation': 1516, 'low_point': 'little river', 'low_elevation': 87},
            {'state': 'oregon', 'abbreviation': 'or', 'high_point': 'mount hood', 'high_elevation': 3424, 'low_point': 'pacific ocean', 'low_elevation': 0},
            {'state': 'pennsylvania', 'abbreviation': 'pa', 'high_point': 'mount davis', 'high_elevation': 979, 'low_point': 'delaware river', 'low_elevation': 0},
            {'state': 'rhode island', 'abbreviation': 'ri', 'high_point': 'jerimoth hill', 'high_elevation': 247, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'south carolina', 'abbreviation': 'sc', 'high_point': 'sassafras mountain', 'high_elevation': 1085, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'south dakota', 'abbreviation': 'sd', 'high_point': 'harney peak', 'high_elevation': 2207, 'low_point': 'big stone lake', 'low_elevation': 284},
            {'state': 'tennessee', 'abbreviation': 'tn', 'high_point': 'clingmans dome', 'high_elevation': 2025, 'low_point': 'mississippi river', 'low_elevation': 55},
            {'state': 'texas', 'abbreviation': 'tx', 'high_point': 'guadalupe peak', 'high_elevation': 2667, 'low_point': 'gulf of mexico', 'low_elevation': 0},
            {'state': 'utah', 'abbreviation': 'ut', 'high_point': 'kings peak', 'high_elevation': 4123, 'low_point': 'beaver dam creek', 'low_elevation': 610},
            {'state': 'vermont', 'abbreviation': 'vt', 'high_point': 'mount mansfield', 'high_elevation': 1339, 'low_point': 'lake champlain', 'low_elevation': 29},
            {'state': 'virginia', 'abbreviation': 'va', 'high_point': 'mount rogers', 'high_elevation': 1746, 'low_point': 'atlantic ocean', 'low_elevation': 0},
            {'state': 'washington', 'abbreviation': 'wa', 'high_point': 'mount rainier', 'high_elevation': 4392, 'low_point': 'pacific ocean', 'low_elevation': 0},
            {'state': 'west virginia', 'abbreviation': 'wv', 'high_point': 'spruce knob', 'high_elevation': 1482, 'low_point': 'potomac river', 'low_elevation': 73},
            {'state': 'wisconsin', 'abbreviation': 'wi', 'high_point': 'timms hill', 'high_elevation': 595, 'low_point': 'lake michigan', 'low_elevation': 177},
            {'state': 'wyoming', 'abbreviation': 'wy', 'high_point': 'gannett peak', 'high_elevation': 4202, 'low_point': 'belle fourche river', 'low_elevation': 945},
            ]

mountains = [   {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'mckinley', 'elevation': 6194},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'st. elias', 'elevation': 5489},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'foraker', 'elevation': 5304},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'bona', 'elevation': 5044},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'blackburn', 'elevation': 4996},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'kennedy', 'elevation': 4964},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'sanford', 'elevation': 4949},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'south buttress', 'elevation': 4842},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'vancouver', 'elevation': 4785},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'churchill', 'elevation': 4766},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'fairweather', 'elevation': 4663},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'hubbard', 'elevation': 4577},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'bear', 'elevation': 4520},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'east buttress', 'elevation': 4490},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'hunter', 'elevation': 4442},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'alverstone', 'elevation': 4439},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'browne tower', 'elevation': 4429},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'whitney', 'elevation': 4418},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'elbert', 'elevation': 4399},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'massive', 'elevation': 4396},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'harvard', 'elevation': 4395},
                {'state': 'washington', 'abbreviation': 'wa', 'mountain': 'rainier', 'elevation': 4392},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'williamson', 'elevation': 4382},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'bianca', 'elevation': 4372},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'la plata', 'elevation': 4370},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'uncompahgre', 'elevation': 4361},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'crestone', 'elevation': 4357},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'lincoln', 'elevation': 4354},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'grays', 'elevation': 4349},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'antero', 'elevation': 4349},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'torreys', 'elevation': 4349},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'castle', 'elevation': 4348},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'quandary', 'elevation': 4348},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'evans', 'elevation': 4348},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'longs', 'elevation': 4345},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'wilson', 'elevation': 4342},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'white', 'elevation': 4342},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'north palisade', 'elevation': 4341},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'shavano', 'elevation': 4337},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'belford', 'elevation': 4327},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'princeton', 'elevation': 4327},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'crestone needle', 'elevation': 4327},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'yale', 'elevation': 4327},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'bross', 'elevation': 4320},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'kit carson', 'elevation': 4317},
                {'state': 'alaska', 'abbreviation': 'ak', 'mountain': 'wrangell', 'elevation': 4317},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'shasta', 'elevation': 4317},
                {'state': 'california', 'abbreviation': 'ca', 'mountain': 'sill', 'elevation': 4317},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'el diente', 'elevation': 4316},
                {'state': 'colorado', 'abbreviation': 'co', 'mountain': 'maroon', 'elevation': 4315},
            ]

lakes = [   {'lake': 'superior', 'area': 82362, 'states': ['michigan', 'wisconsin', 'minnesota']},
            {'lake': 'huron', 'area': 59570, 'states': ['michigan']},
            {'lake': 'michigan', 'area': 58016, 'states': ['michigan', 'indiana', 'illinois', 'wisconsin']},
            {'lake': 'erie', 'area': 25667, 'states': ['new york', 'pennsylvania', 'ohio', 'michigan']},
            {'lake': 'ontario', 'area': 19684, 'states': ['new york']},
            {'lake': 'great salt lake', 'area': 5180, 'states': ['utah']},
            {'lake': 'lake of the woods', 'area': 4391, 'states': ['minnesota']},
            {'lake': 'iliamna', 'area': 2675, 'states': ['alaska']},
            {'lake': 'okeechobee', 'area': 1810, 'states': ['florida']},
            {'lake': 'pontchartrain', 'area': 1632, 'states': ['louisiana']},
            {'lake': 'becharof', 'area': 1186, 'states': ['alaska']},
            {'lake': 'red', 'area': 1169, 'states': ['minnesota']},
            {'lake': 'st. clair', 'area': 1119, 'states': ['michigan']},
            {'lake': 'champlain', 'area': 1114, 'states': ['vermont', 'new york']},
            {'lake': 'rainy', 'area': 932, 'states': ['minnesota']},
            {'lake': 'salton sea', 'area': 932, 'states': ['california']},
            {'lake': 'teshekpuk', 'area': 816, 'states': ['alaska']},
            {'lake': 'naknek', 'area': 630, 'states': ['alaska']},
            {'lake': 'winnebago', 'area': 557, 'states': ['wisconsin']},
            {'lake': 'mille lacs', 'area': 536, 'states': ['minnesota']},
            {'lake': 'flathead', 'area': 510, 'states': ['montana']},
            {'lake': 'tahoe', 'area': 497, 'states': ['nevada', 'california']},
        ]

countries = [ {'country': 'usa', 'population': 307890000, 'area': 9826675},
            ]

# Views to facilitate evaluation
places = [{'state': x['state'], 'abbreviation': x['abbreviation'], 'place': x['high_point'], 'elevation': x['high_elevation']} for x in highlows] + \
         [{'state': x['state'], 'abbreviation': x['abbreviation'], 'place': x['low_point'], 'elevation': x['low_elevation']} for x in highlows] + \
         [{'state': 'california', 'abbreviation': 'ca', 'place': 'mount davidson', 'elevation': 282}]

places_and_mountains = [{'state': x['state'], 'abbreviation': x['abbreviation'], 'element': x['place'], 'elevation': x['elevation']} for x in places] + \
                       [{'state': x['state'], 'abbreviation': x['abbreviation'], 'element': x['mountain'], 'elevation': x['elevation']} for x in mountains]

cities_and_capitals = [{'state': x['state'], 'abbreviation': x['abbreviation'], 'city': x['city']} for x in cities] + \
                      [{'state': x['state'], 'abbreviation': x['abbreviation'], 'city': x['capital']} for x in states] + \
                      [{'state': x['state'], 'abbreviation': x['abbreviation'], 'city': y} for x in states for y in x['cities']]